### PR TITLE
Fix stepping for dart

### LINKED ISSUE #272: Stepping in Dart is janky
I've disabled it on the website, but someone needs to figure out what's wrong.

### PR DESCRIPTION
**Pull request by baxtersa**
Fixes #272 

We can redeploy the stopify compiler cloud function once this lands.

### CODE REVIEW

File: stopify/src/compile.ts [hunk 1]
```diff
@@ -60,7 +60,7 @@ commander.arguments('<srcPath> <dstPath>');
 const args = commander.parse(process.argv);
 
 stopify(args.args[0], {
-  debug: args.boolean,
```
Comment (baxtersa) [inline stopify/src/compile.ts]: This would have broken all the debugging languages, I guess the stopify bundle hasn't been redeployed with this change yet?

File: stopify/src/common/helpers.ts [hunk 2]
```diff
@@ -173,6 +173,8 @@ function generateLineMapping(map: RawSourceMap | undefined): LineMapping {
         mapping.source.includes('https://') ||
         mapping.source.includes('goog/') ||
         mapping.source.includes('cljs/') ||
+        mapping.source.includes('opt/') ||
+        mapping.source.includes('user_code/') ||
```
Comment (arjunguha) [inline stopify/src/common/helpers.ts]:
```
............................................________........................ 
....................................,.-‘”...................``~.,.................. 
.............................,.-”...................................“-.,............ 
.........................,/...............................................”:,........ 
.....................,?......................................................\,..... 
.................../...........................................................,}.... 
................./......................................................,:`^`..}.... 
.............../...................................................,:”........./..... 
..............?.....__.........................................:`.........../..... 
............./__.(.....“~-,_..............................,:`........../........ 
.........../(_....”~,_........“~,_....................,:`........_/........... 
..........{.._$;_......”=,_.......“-,_.......,.-~-,},.~”;/....}........... 
...........((.....*~_.......”=-._......“;,,./`..../”............../............ 
...,,,___.\`~,......“~.,....................`.....}............../............. 
............(....`=-,,.......`........................(......;_,,-”............... 
............/.`~,......`-...............................\....../\................... 
.............\`~.*-,.....................................|,./.....\,__........... 
,,_..........}.>-._\...................................|..............`=~-,.... 
.....`=~-,_\_......`\,.................................\........................ 
...................`=~-,,.\,...............................\....................... 
................................`:,,...........................`\..............__.. 
.....................................`=-,...................,%`>--==``....... 
........................................_\..........._,-%.......`\............... 
...................................,<`.._|_,-&``................`\..............
```

Comment (rachitnigam) [reply stopify/src/common/helpers.ts]: What is that?

Comment (baxtersa) [reply stopify/src/common/helpers.ts]: facepalm

Comment (rachitnigam) [reply stopify/src/common/helpers.ts]: ah
